# Generated by Django 6.0.4 on 2026-04-18 21:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_landmark_latitude_landmark_longitude_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='accessibility_level',
            field=models.CharField(choices=[('full', 'Fully accessible'), ('partial', 'Partially accessible'), ('limited', 'Limited accessibility')], default='partial', max_length=20, verbose_name='Accessibility'),
        ),
        migrations.AddField(
            model_name='landmark',
            name='category',
            field=models.CharField(choices=[('history', 'History'), ('nature', 'Nature'), ('culture', 'Culture'), ('adventure', 'Adventure'), ('wellness', 'Wellness'), ('city', 'City')], default='culture', max_length=30, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='landmark',
            name='family_friendly',
            field=models.BooleanField(default=False, verbose_name='Family friendly'),
        ),
        migrations.AddField(
            model_name='landmark',
            name='physical_intensity',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Physical intensity'),
        ),
        migrations.AddField(
            model_name='landmark',
            name='recommended_visit_hours',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Recommended visit duration'),
        ),
        migrations.AddField(
            model_name='landmark',
            name='senior_friendly',
            field=models.BooleanField(default=False, verbose_name='Senior friendly'),
        ),
        migrations.AddField(
            model_name='landmark',
            name='theme_tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Theme tags'),
        ),
        migrations.CreateModel(
            name='ARMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Title (English)')),
                ('title_ky', models.CharField(blank=True, max_length=200, verbose_name='Title (Kyrgyz)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_ky', models.TextField(blank=True, verbose_name='Description (Kyrgyz)')),
                ('marker_type', models.CharField(choices=[('reconstruction', 'Historical reconstruction'), ('costume', 'Traditional costume'), ('story', 'Story hotspot'), ('panorama', 'Panoramic guide')], default='story', max_length=30, verbose_name='Marker type')),
                ('icon', models.CharField(default='sparkles', max_length=30, verbose_name='Icon name')),
                ('distance_meters', models.PositiveSmallIntegerField(default=20, verbose_name='Distance hint (m)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sort order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_markers', to='attractions.landmark', verbose_name='Landmark')),
            ],
            options={
                'verbose_name': 'AR marker',
                'verbose_name_plural': 'AR markers',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
